# -*- coding: utf-8 -*-
"""Excel Cleaning Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScnAHYk7VFrs6Dzpqb17aW7XOoSzKRrj
"""

# Cell 1 — Install jika perlu
!pip install pandas openpyxl numpy --quiet

# Cell 2 — Import library
import pandas as pd
import numpy as np
import io, os, re
from google.colab import files
from google.colab import drive

# Cell 3 — Pilihan: upload file lokal atau mount Google Drive
print("Pilih metode input file:")
print("1) Upload file dari komputer (recommended untuk sekali pakai).")
print("2) Mount Google Drive (jika file besar / sering dipakai).")

method = "upload"  # Ubah ke "drive" jika mau mount. (atau ubah secara interaktif sebelum run)

# Jika ingin mount, uncomment baris berikut:
# drive.mount('/content/drive')

# Cell 4 — Upload file (jika method = upload)
if method == "upload":
    print("Silakan upload file Excel/CSV (contoh: data.xlsx atau data.csv)")
    uploaded = files.upload()  # dialog upload
    # ambil nama file pertama
    filename = list(uploaded.keys())[0]
    print("File terupload:", filename)
else:
    # contoh path jika sudah mount drive
    filename = '/content/drive/MyDrive/FolderSaya/data_ispu.xlsx'
    print("Menggunakan file di Drive:", filename)

# Cell 5 — Fungsi pembersih umum
def clean_air_quality_file(path_or_buffer, sheet_name=0, prefer_csv_delimiter='auto'):
    """
    Membaca file Excel/CSV, membersihkan token bermasalah, menormalkan header,
    mengonversi kolom numerik, dan mengembalikan DataFrame plus dua versi CSV.
    prefer_csv_delimiter: 'auto', ',' or ';'
    """
    # detect by extension
    if isinstance(path_or_buffer, str) and path_or_buffer.lower().endswith(('.xls','.xlsx')):
        df = pd.read_excel(path_or_buffer, sheet_name=sheet_name, dtype=str)
    else:
        # handle buffer or file path as CSV — try auto sniff delimiter
        sample = None
        if isinstance(path_or_buffer, str):
            with open(path_or_buffer, 'r', encoding='utf-8', errors='replace') as f:
                sample = f.read(2048)
        else:
            # buffer
            sample = path_or_buffer.read(2048).decode('utf-8', errors='replace')
            path_or_buffer.seek(0)
        # sniff
        if prefer_csv_delimiter!='auto':
            delim = prefer_csv_delimiter
        else:
            # choose semicolon if more ; than ,
            if sample.count(';') >= sample.count(','):
                delim = ';'
            else:
                delim = ','
        df = pd.read_csv(path_or_buffer, sep=delim, dtype=str, keep_default_na=False, na_values=[])

    # BASIC NORMALIZATION OF HEADER (lowercase, replace spaces->underscore)
    df.columns = [re.sub(r'\s+','_',c.strip().lower()) for c in df.columns]

    # common token replacements to treat as NULL
    df = df.replace({"N/A": pd.NA, "NA": pd.NA, "null": pd.NA, "n/a": pd.NA, "": pd.NA})

    # Trim whitespace in string columns
    df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

    # Map header name variations to expected names (customize jika perlu)
    expected = ['parameter_pencemar_kritis','kategori','periode_data','bulan','tanggal','stasiun',
                'pm_sepuluh','pm_duakomalima','sulfur_dioksida','karbon_monoksida','ozon',
                'nitrogen_dioksida','max']
    # automatic mapping: a column that contains substring
    mapping = {}
    for ec in expected:
        for col in df.columns:
            if ec in col or col.startswith(ec[:6]):
                mapping[col] = ec
                break
    # apply if any
    if mapping:
        df = df.rename(columns=mapping)

    # Force numeric conversion on known numeric columns
    numeric_cols = ['pm_sepuluh','pm_duakomalima','sulfur_dioksida','karbon_monoksida','ozon','nitrogen_dioksida','max']
    for c in numeric_cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors='coerce')  # invalid -> NaN

    # Reorder columns if expected available
    final_cols = [c for c in expected if c in df.columns]
    other_cols = [c for c in df.columns if c not in final_cols]
    df = df[final_cols + other_cols]

    return df

# Cell 6 — Jalankan pembersihan pada file yang diupload
df = clean_air_quality_file(filename, prefer_csv_delimiter='auto')
print("Preview data:")
display(df.head())
print("Jumlah baris:", len(df))

# Cell 7 — Simpan ke CSV bersih (semicolon & comma)
out_semicolon = "air_quality_cleaned_semicolon.csv"
out_comma     = "air_quality_cleaned_comma.csv"
df.to_csv(out_semicolon, sep=';', index=False, na_rep='')
df.to_csv(out_comma, sep=',', index=False, na_rep='')
print("File disimpan:", out_semicolon, out_comma)

# Cell 8.1 — Download link yang benar-benar bekerja di Google Colab

from google.colab import files

# Pastikan nama variabel sesuai
files.download(out_semicolon)

# Cell 8.2  — Download link yang benar-benar bekerja di Google Colab

from google.colab import files

# Pastikan nama variabel sesuai
files.download(out_comma)

# Cell 9 — Optional: preview summary statistik (cek numeric)
print(df.describe(include='all'))

# Cell 10 — Optional: export ke Google Drive (jika mount dilakukan)

# contoh: dst = '/content/drive/MyDrive/air_quality_cleaned_semicolon.csv'
# df.to_csv(dst, sep=';', index=False, na_rep='')